services:
  # PHP Service for Laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_nedhelps
    expose:
      - 9000
    volumes:
      - .:/var/www
    environment:
      - DATABASE_URL=mysql://root:password@mysql/nedhelps

  # Nginx Service for Laravel
  webserver:
    image: nginx:alpine
    container_name: webserver_nedhelps
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: mysql_nedhelps
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: nedhelps
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    container_name: phpmyadmin_nedhelps
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

volumes:
  dbdata:
    driver: local
